publisher:
  name: 'Textus Classics'
publication:
  date: 2017
  copyright: 'This work is in the Public Domain, free of copyrights.'
  dedication: 'Dedicated to the Internet.'
  colophon: 'Textus Classics Bicentenary Edition'
  author:
    about: 'Jane Austen (1775–1817) was an English novelist known primarily for her six major novels, which interpret, critique and comment upon the British landed gentry at the end of the eighteenth century. Austen’s plots often explore the dependence of women on marriage in the pursuit of favourable social standing and economic security. Her works critique the novels of sensibility of the second half of the eighteenth century and are part of the transition to nineteenth-century literary realism. (Wikipedia.org'
